[build]
  publish = "dist/"
  command = "npm run build"

[[headers]]
  for = "/*"

  [headers.values]
    Strict-Transport-Security = "max-age=63072000;includeSubDomains;preload"
    Access-Control-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"

# Older revisions had these URLs working.

[[redirects]]
  from = "/:year/:month/:day/:post/"
  to = "/:post"

[[redirects]]
  from = "/blog/archives/"
  to = "/archives/"

[[redirects]]
  from = "https://blog.domenic.me/atom.xml"
  to = "/feed.xml"

[[redirects]]
  from = "/atom.xml"
  to = "/feed.xml"

[[redirects]]
  from = "https://blog.domenic.me/categories/node-dot-js"
  to = "/categories/javascript"

[[redirects]]
  from = "https://blog.domenic.me/categories/node-js"
  to = "/categories/javascript"

[[redirects]]
  from = "https://blog.domenic.me/categories/node.js"
  to = "/categories/javascript"

[[redirects]]
  from = "https://blog.domenic.me/categories/promises"
  to = "/categories/javascript"

[[redirects]]
  from = "https://blog.domenic.me/categories/web"
  to = "/categories/web-standards"

[[redirects]]
  from = "https://blog.domenic.me/categories/streams"
  to = "/categories/web-standards"

[[redirects]]
  from = "https://blog.domenic.me/categories/not-software"
  to = "/categories/other"

[[redirects]]
  from = "https://blog.domenic.me/categories/open-source"
  to = "/categories/other"

[[redirects]]
  from = "https://blog.domenic.me/categories/ai"
  to = "/categories/other"

# For most of the site's life, after a brief stint on https://domenic.me, everything was hosted on https://blog.domenic.me. Now we're back on https://domenic.me.

[[redirects]]
  from = "https://blog.domenic.me/*"
  to = "https://domenic.me/:splat"
  force = true
