[build]
  publish = "dist/"
  command = "npm run build"

[[headers]]
  for = "/*"

  [headers.values]
    Strict-Transport-Security = "max-age=63072000;includeSubDomains;preload"
    Access-Control-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"

# In its earliest days the blog was hosted on domenic.me directly, and used
# dates in the post URLs.

[[redirects]]
  from = "https://domenic.me/201:rest-of-date/:post/"
  to = "https://blog.domenic.me/:post"

[[redirects]]
  from = "https://domenic.me/categories/:category"
  to = "https://blog.domenic.me/categories/:category"

[[redirects]]
  from = "https://domenic.me/blog/archives/"
  to = "https://blog.domenic.me/"

# Any hit to domenic.me that isn't covered by the above should 302 to the blog.
# Maybe one day domenic.me will have independent content.

[[redirects]]
  from = "https://domenic.me/*"
  to = "https://blog.domenic.me/:splat"
  status = 302

# Older revisions of the blog had these URLs working

[[redirects]]
  from = "/archives"
  to = "/"

[[redirects]]
  from = "/categories/node-dot-js"
  to = "/categories/node.js"

[[redirects]]
  from = "/categories/node-js"
  to = "/categories/node.js"
